using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Platform.API.OAuth;

/// <summary>
/// Provides the platform's OAuth 2.0 authorization-code + PKCE flow operations.
/// </summary>
/// <remarks>
/// Typical usage:
/// <list type="number">
///   <item><description>
///   Call <see cref="BuildAuthorizationUrl"/> to get the URL to redirect the user to. To also
///   request a protected-resource permission (e.g. <c>highlights</c>) as part of this same
///   sign-in, pass it via <c>requestedPermissions</c> — the consent UI is shown alongside sign-in,
///   and the callback carries a <c>granted_permissions</c> query parameter alongside <c>code</c>.
///   </description></item>
///   <item><description>
///   The user authenticates and is redirected back. For confidential/server clients this
///   carries a <c>code</c> query parameter directly — call <see cref="ExchangeCodeAsync"/> with
///   it. Browser clients instead get an identity-only redirect (<c>yvp_id</c>, <c>user_name</c>,
///   <c>user_email</c>, <c>profile_picture</c>, <c>state</c> — no <c>code</c>); call
///   <see cref="CompleteIdentityCallbackAsync"/> with those fields instead, which obtains the
///   code via a second hop and redeems it internally.
///   </description></item>
///   <item><description>Either way, the resulting token is automatically stored via <see cref="ITokenProvider"/>.</description></item>
///   <item><description>
///   To request a protected-resource permission separately, after the user is already signed in
///   (skipping a full sign-in round trip), call <see cref="RequestPermissionsAsync"/> and redirect
///   the user to <see cref="BuildDataExchangeApprovalUrl"/> instead — a standalone consent step.
///   Once approved, the same access token is authorized for that resource.
///   </description></item>
///   <item><description>
///   The platform redirects the browser back to your configured callback URL with the outcome.
///   Call <see cref="ParseDataExchangeCallback"/> on that URL to find out whether the requested
///   permissions were granted, denied, or errored. A confidential client can instead skip the
///   browser entirely by calling <see cref="CompleteDataExchangeApprovalAsync"/> with the token
///   from step 4 directly.
///   </description></item>
///   <item><description>Call <see cref="RefreshTokenAsync"/> proactively, or rely on <c>OAuthBearerTokenHandler</c> to refresh transparently.</description></item>
///   <item><description>Call <see cref="SignOutAsync"/> to clear the stored token on sign-out.</description></item>
/// </list>
/// </remarks>
public interface IBibleOAuthClient
{
    /// <summary>
    /// Builds the authorization URL and PKCE values needed to start the sign-in flow.
    /// </summary>
    /// <param name="state">
    /// Optional opaque state string for CSRF protection. If omitted, a random value is generated.
    /// Verify this value matches the <c>state</c> parameter on the callback.
    /// </param>
    /// <param name="requestedPermissions">
    /// Optional resource permissions (e.g. <c>"highlights"</c>) to request consent for during this
    /// same sign-in redirect. When supplied, the user sees the permission consent UI as part of
    /// sign-in, and the callback carries a <c>granted_permissions</c> query parameter (comma-separated,
    /// empty if none were granted, omitted if none were requested) alongside <c>code</c>/<c>state</c>.
    /// This is an alternative to the separate <see cref="RequestPermissionsAsync"/> +
    /// <see cref="BuildDataExchangeApprovalUrl"/> flow, which is for requesting additional
    /// permissions after the user is already signed in.
    /// </param>
    /// <returns>
    /// An <see cref="AuthorizationRequest"/> containing the URL to redirect the user to
    /// and the <see cref="PkceValues"/> to store server-side for the token exchange step.
    /// </returns>
    AuthorizationRequest BuildAuthorizationUrl(string? state = null, IEnumerable<string>? requestedPermissions = null);

    /// <summary>
    /// Verifies that the <c>state</c> value returned by the identity provider on the OAuth
    /// callback matches the value generated by <see cref="BuildAuthorizationUrl"/> and persisted
    /// by the caller across the redirect, guarding against CSRF.
    /// </summary>
    /// <param name="expectedState">The state value the caller persisted after calling <see cref="BuildAuthorizationUrl"/>.</param>
    /// <param name="actualState">The <c>state</c> query parameter received on the callback.</param>
    /// <returns>
    /// <see langword="true"/> if both values are non-empty and match; otherwise <see langword="false"/>.
    /// A missing <paramref name="expectedState"/> (e.g. an expired session) fails the check rather
    /// than being treated as "nothing to verify".
    /// </returns>
    bool ValidateState(string? expectedState, string? actualState);

    /// <summary>
    /// Exchanges an authorization code for access and refresh tokens.
    /// The resulting token is stored via <see cref="ITokenProvider"/>.
    /// </summary>
    /// <param name="code">The authorization code received in the redirect callback.</param>
    /// <param name="codeVerifier">The PKCE code verifier from the matching <see cref="PkceValues"/>.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The <see cref="OAuthTokenResponse"/> containing the access and refresh tokens.</returns>
    Task<OAuthTokenResponse> ExchangeCodeAsync(
        string code,
        string codeVerifier,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Completes the identity-only redirect that browser clients get back from
    /// <see cref="BuildAuthorizationUrl"/> (<c>yvp_id</c>, <c>user_name</c>, <c>user_email</c>,
    /// <c>profile_picture</c>, and <c>state</c> query parameters — no <c>code</c>). This is step 2
    /// of the platform's documented sign-in flow (https://developers.youversion.com/sign-in-apis):
    /// it sends those identity fields to the callback endpoint to obtain a real authorization
    /// <c>code</c>, then redeems that code via <see cref="ExchangeCodeAsync"/> (step 3). The
    /// resulting token is stored via <see cref="ITokenProvider"/>, same as <see cref="ExchangeCodeAsync"/>.
    /// </summary>
    /// <param name="state">The <c>state</c> query parameter received on the identity redirect.</param>
    /// <param name="yvpId">The <c>yvp_id</c> query parameter received on the identity redirect.</param>
    /// <param name="userName">The <c>user_name</c> query parameter, if present.</param>
    /// <param name="userEmail">The <c>user_email</c> query parameter, if present.</param>
    /// <param name="profilePicture">The <c>profile_picture</c> query parameter, if present.</param>
    /// <param name="codeVerifier">The PKCE code verifier from the matching <see cref="PkceValues"/>.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The <see cref="OAuthTokenResponse"/> containing the access and refresh tokens.</returns>
    /// <exception cref="ArgumentException">Thrown when <paramref name="state"/>, <paramref name="yvpId"/>, or <paramref name="codeVerifier"/> is empty.</exception>
    Task<OAuthTokenResponse> CompleteIdentityCallbackAsync(
        string state,
        string yvpId,
        string? userName,
        string? userEmail,
        string? profilePicture,
        string codeVerifier,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Uses the stored refresh token to obtain a new access token.
    /// The new token is stored via <see cref="ITokenProvider"/>.
    /// </summary>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The refreshed <see cref="OAuthTokenResponse"/>.</returns>
    /// <exception cref="InvalidOperationException">Thrown when no refresh token is available.</exception>
    Task<OAuthTokenResponse> RefreshTokenAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Clears the stored token. Call this on user sign-out.
    /// </summary>
    Task SignOutAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Requests a short-lived Data Exchange token for one or more resource permissions (e.g.
    /// <c>highlights</c>), using the currently stored access token. Pass the returned token's
    /// <see cref="DataExchangeToken.Token"/> to <see cref="BuildDataExchangeApprovalUrl"/> to get
    /// the URL the user must visit to grant or deny the request.
    /// </summary>
    /// <param name="permissions">The resource permissions being requested (e.g. <c>"highlights"</c>).</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The short-lived <see cref="DataExchangeToken"/>.</returns>
    /// <exception cref="InvalidOperationException">Thrown when no access token is stored.</exception>
    Task<DataExchangeToken> RequestPermissionsAsync(
        IEnumerable<string> permissions,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Builds the URL to redirect the user to for the Data Exchange approval page.
    /// </summary>
    /// <remarks>
    /// The approval page is a top-level browser redirect, so it cannot rely on the
    /// <c>X-YVP-App-Key</c> header the rest of the SDK sends — the app key is included as an
    /// <c>x-yvp-app-key</c> query parameter instead, sourced from the configured
    /// <c>BibleApiOptions.AppKey</c>.
    /// </remarks>
    /// <param name="dataExchangeToken">The <see cref="DataExchangeToken.Token"/> from <see cref="RequestPermissionsAsync"/>.</param>
    /// <returns>The approval page URL.</returns>
    /// <exception cref="InvalidOperationException">Thrown when <c>BibleApiOptions.AppKey</c> is not configured.</exception>
    Uri BuildDataExchangeApprovalUrl(string dataExchangeToken);

    /// <summary>
    /// Builds a "direct browser flow" Data Exchange URL: <c>GET /data-exchange</c> called with only
    /// <c>x-yvp-app-key</c> and <c>requested_permissions</c> — no pre-issued Data Exchange
    /// <c>token</c>, and therefore no prior sign-in round trip via <see cref="BuildAuthorizationUrl"/>.
    /// </summary>
    /// <remarks>
    /// The documented schema for <c>GET /data-exchange</c> marks <c>token</c> as required (it's
    /// normally created via <see cref="RequestPermissionsAsync"/>, which itself requires an
    /// existing access token). This method is for apps with no way to obtain that prior access
    /// token at all — the platform's server-observed behavior for this app/client is to run its own
    /// identity check and permission consent inline and redirect back with identity fields
    /// (<c>yvp_id</c>, <c>user_name</c>, <c>user_email</c>) and/or <c>granted_permissions</c>
    /// rather than a redeemable <c>code</c> or <c>access_token</c> — i.e. this path authenticates
    /// the user and confirms permission grants, but does not itself yield a bearer token.
    /// </remarks>
    /// <param name="permissions">The resource permissions being requested (e.g. <c>"highlights"</c>).</param>
    /// <param name="state">Optional opaque state string for CSRF protection.</param>
    /// <returns>The URL to redirect the user to.</returns>
    /// <exception cref="ArgumentException">Thrown when <paramref name="permissions"/> is empty.</exception>
    /// <exception cref="InvalidOperationException">Thrown when <c>BibleApiOptions.AppKey</c> is not configured.</exception>
    Uri BuildDirectDataExchangeUrl(IEnumerable<string> permissions, string? state = null);

    /// <summary>
    /// Parses the query parameters the platform appends to your configured callback URL after a
    /// user completes (or cancels) the Data Exchange approval page.
    /// </summary>
    /// <param name="callbackUrl">The full callback URL, including its query string, that the browser was redirected to.</param>
    /// <returns>The parsed outcome.</returns>
    DataExchangeCallbackResult ParseDataExchangeCallback(Uri callbackUrl);

    /// <summary>
    /// Completes a Data Exchange approval using a previously-issued Data Exchange token instead of
    /// sending the user through the browser-rendered approval page. Intended for confidential
    /// clients that already have another basis for the user's consent.
    /// </summary>
    /// <remarks>
    /// <c>POST /data-exchange</c> takes no request body — the permissions being granted are the
    /// ones fixed when <paramref name="dataExchangeToken"/> was created via
    /// <see cref="RequestPermissionsAsync"/>, so they aren't (and can't be) sent again here.
    /// </remarks>
    /// <param name="dataExchangeToken">The <see cref="DataExchangeToken.Token"/> from <see cref="RequestPermissionsAsync"/>.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The parsed outcome, extracted from the API's <c>303</c> redirect response.</returns>
    /// <exception cref="ArgumentException">Thrown when <paramref name="dataExchangeToken"/> is empty.</exception>
    /// <exception cref="InvalidOperationException">Thrown when <c>BibleApiOptions.AppKey</c> is not configured.</exception>
    Task<DataExchangeCallbackResult> CompleteDataExchangeApprovalAsync(
        string dataExchangeToken,
        CancellationToken cancellationToken = default);
}
