using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Platform.API.OAuth;

/// <summary>
/// Provides YouVersion OAuth 2.0 authorization-code + PKCE flow operations.
/// </summary>
/// <remarks>
/// Typical usage:
/// <list type="number">
///   <item><description>Call <see cref="BuildAuthorizationUrl"/> to get the URL to redirect the user to.</description></item>
///   <item><description>The user authenticates and is redirected back with a <c>code</c> query parameter.</description></item>
///   <item><description>Call <see cref="ExchangeCodeAsync"/> with that code. The resulting token is automatically stored via <see cref="ITokenProvider"/>.</description></item>
///   <item><description>
///   Sign-in alone only grants identity. To access a protected resource (e.g. highlights), call
///   <see cref="RequestPermissionsAsync"/> and redirect the user to
///   <see cref="BuildDataExchangeApprovalUrl"/> — a separate consent step. Once the user approves,
///   the same access token from step 3 is authorized for that resource.
///   </description></item>
///   <item><description>Call <see cref="RefreshTokenAsync"/> proactively, or rely on <c>OAuthBearerTokenHandler</c> to refresh transparently.</description></item>
///   <item><description>Call <see cref="SignOutAsync"/> to clear the stored token on sign-out.</description></item>
/// </list>
/// </remarks>
public interface IYouVersionOAuthClient
{
    /// <summary>
    /// Builds the authorization URL and PKCE values needed to start the sign-in flow.
    /// </summary>
    /// <param name="state">
    /// Optional opaque state string for CSRF protection. If omitted, a random value is generated.
    /// Verify this value matches the <c>state</c> parameter on the callback.
    /// </param>
    /// <returns>
    /// An <see cref="AuthorizationRequest"/> containing the URL to redirect the user to
    /// and the <see cref="PkceValues"/> to store server-side for the token exchange step.
    /// </returns>
    AuthorizationRequest BuildAuthorizationUrl(string? state = null);

    /// <summary>
    /// Verifies that the <c>state</c> value returned by the identity provider on the OAuth
    /// callback matches the value generated by <see cref="BuildAuthorizationUrl"/> and persisted
    /// by the caller across the redirect, guarding against CSRF.
    /// </summary>
    /// <param name="expectedState">The state value the caller persisted after calling <see cref="BuildAuthorizationUrl"/>.</param>
    /// <param name="actualState">The <c>state</c> query parameter received on the callback.</param>
    /// <returns>
    /// <see langword="true"/> if both values are non-empty and match; otherwise <see langword="false"/>.
    /// A missing <paramref name="expectedState"/> (e.g. an expired session) fails the check rather
    /// than being treated as "nothing to verify".
    /// </returns>
    bool ValidateState(string? expectedState, string? actualState);

    /// <summary>
    /// Exchanges an authorization code for access and refresh tokens.
    /// The resulting token is stored via <see cref="ITokenProvider"/>.
    /// </summary>
    /// <param name="code">The authorization code received in the redirect callback.</param>
    /// <param name="codeVerifier">The PKCE code verifier from the matching <see cref="PkceValues"/>.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The <see cref="OAuthTokenResponse"/> containing the access and refresh tokens.</returns>
    Task<OAuthTokenResponse> ExchangeCodeAsync(
        string code,
        string codeVerifier,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Uses the stored refresh token to obtain a new access token.
    /// The new token is stored via <see cref="ITokenProvider"/>.
    /// </summary>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The refreshed <see cref="OAuthTokenResponse"/>.</returns>
    /// <exception cref="InvalidOperationException">Thrown when no refresh token is available.</exception>
    Task<OAuthTokenResponse> RefreshTokenAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Clears the stored token. Call this on user sign-out.
    /// </summary>
    Task SignOutAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Requests a short-lived Data Exchange token for one or more resource permissions (e.g.
    /// <c>highlights</c>), using the currently stored access token. Pass the returned token's
    /// <see cref="DataExchangeToken.Token"/> to <see cref="BuildDataExchangeApprovalUrl"/> to get
    /// the URL the user must visit to grant or deny the request.
    /// </summary>
    /// <param name="permissions">The resource permissions being requested (e.g. <c>"highlights"</c>).</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The short-lived <see cref="DataExchangeToken"/>.</returns>
    /// <exception cref="InvalidOperationException">Thrown when no access token is stored.</exception>
    Task<DataExchangeToken> RequestPermissionsAsync(
        IEnumerable<string> permissions,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Builds the URL to redirect the user to for the Data Exchange approval page.
    /// </summary>
    /// <param name="dataExchangeToken">The <see cref="DataExchangeToken.Token"/> from <see cref="RequestPermissionsAsync"/>.</param>
    /// <returns>The approval page URL.</returns>
    Uri BuildDataExchangeApprovalUrl(string dataExchangeToken);
}
